package compilador.lexico;

public enum TokenType {
	LINE_COMMENT, BLOCK_COMMENT_BEGIN, BLOCK_COMMENT_END, NEW_LINE, IDENTIFIER, UNSIGNED_NUMBER, PUNCTUATION, OPERATOR, SPECIAL_CHARACTER, SPECIAL_CHARACTER_COMBINATION;
}
